name: Build Check

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'README.md'
      - '.github/*.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'README.md'
      - '.github/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.changed_files, 'README.md') && github.event_name != 'push' || github.event_name == 'push' && !contains(github.event.head_commit.modified, 'README.md') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Check flake is valid
        run: nix flake check

      - name: Build kernel
        run: nix build .#linux-bazzite --show-trace

      - name: Add swap space
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Build kernel
        run: nix build .#linux-bazzite --show-trace